### ISSUE TITLE
Реализовать функционал @Retry

### ISSUE THREAD

**Issue by Alex05632** [qameta/atlas#17]
Реализовать функционал @Retry для ожидания появления отдельного элемента.
Пример:
@Retry(timeoutInSeconds = 20, pollingInMillis = 500)
AtlasWebElement button();

**Comment by artsok** [comment]
Это уже есть.
```
/**
 * Retry configuration.
 */
@Retention(RetentionPolicy.RUNTIME)
@java.lang.annotation.Target(ElementType.METHOD)
public @interface Retry {

    long timeout() default 5000L;

    long polling() default 1000L;

    Class<? extends Throwable>[] ignoring() default {Throwable.class};

}

```

Использование:

```
    @Retry(timeout = 20000L)
    @IOSFindBy(xpath = "//XCUIElementTypeSearchField[@name='Search Wikipedia']")
    @AndroidFindBy(xpath = "//*[contains(@text, 'Search Wikipedia')]")
    AtlasMobileElement searchWikipedia();

```

**Comment by artsok** [comment]
@Alex05632 Закрой тикет, если не актуально более. Спасибо

**Comment by PavelSukh** [comment]
> Это уже есть.
> 
> ```
> /**
>  * Retry configuration.
>  */
> @Retention(RetentionPolicy.RUNTIME)
> @java.lang.annotation.Target(ElementType.METHOD)
> public @interface Retry {
> 
>     long timeout() default 5000L;
> 
>     long polling() default 1000L;
> 
>     Class<? extends Throwable>[] ignoring() default {Throwable.class};
> 
> }
> ```
> 
> Использование:
> 
> ```
>     @Retry(timeout = 20000L)
>     @IOSFindBy(xpath = "//XCUIElementTypeSearchField[@name='Search Wikipedia']")
>     @AndroidFindBy(xpath = "//*[contains(@text, 'Search Wikipedia')]")
>     AtlasMobileElement searchWikipedia();
> ```

Привет, у меня не работает данная конструкция:
`elementWait().isDisplayed();`
`@Retry(timeout = 60000L)
  @AndroidFindBy(xpath = "//*[contains(@text, 'ORAB-LOGO')]")
  AtlasMobileElement elementWait();`
Ждет 10 секунд как описано в глобальном ожидании
`(new DefaultRetryer(10000L, 1000L, Collections.singletonList(Throwable.class)))`
и после тест падает.
