### ISSUE TITLE
Atlas uses internal Selenium deprecated interfaces 

### ISSUE THREAD

**Issue by KroArtem** [qameta/atlas#68]
Selenium guys recommend not to use internal stuff that is deprecated and will be removed in future.
As a proof, @shs96c said about it in his speech, see more here: https://www.youtube.com/watch?v=cSx9Fd8LEm4

`import org.openqa.selenium.internal.WrapsDriver;` -> 
`import org.openqa.selenium.WrapsDriver;`

`import org.openqa.selenium.interactions.internal.Coordinates;` -> 
`import org.openqa.selenium.interactions.Coordinates;`

`import org.openqa.selenium.interactions.internal.Locatable;` ->
 `import org.openqa.selenium.interactions.Locatable;`

I've made a fix, it's trivial, although I still need answers to tickets #66, #67

**Comment by artsok** [comment]
Yes, are right. In last version of Selenium, these interfaces moved. Will be fix it.
