### ISSUE TITLE
org.apache.httpcomponents:httpclient is a transitive dependency

### ISSUE THREAD

**Issue by KroArtem** [qameta/atlas#69]
org.apache.httpcomponents:httpclient comes to atlas as a transitive dependency from selenium. HttpClient is used in the library so it sounds reasonable to define this as a direct dependency.

**Comment by artsok** [comment]
We was discussing this situation, but didn't have final decision. Why do you think to make it transitive library?

**Comment by KroArtem** [comment]
I mean currently `HttpClient` is not defined in libraries. For example, try to find from where comes 
`import org.apache.http.client.utils.URIBuilder;`

Right now httpclient is a transitive dependency that comes from selenium. I suggest to make it a direct dependency as it's used in Atlas.

**Comment by KroArtem** [comment]
This one has been fixed in master (via #73)
